---
- name: spring-petclinic 
  box: centos/7
  cpus: 2
  memory: 4096 
  private_ip: 10.0.10.10
  package_manager: yum
  packages:
  - docker
# java, maven and git are only needed if you are
# building the docker images locally
#  - java
#  - maven
#  - git
  scripts:
  - docker
  - docker_compose
# uncomment the scripts below to build the docker
# images locally instead of downloading them from dockerhub
#  - spring_petclinic_angular
#  - spring_petclinic_rest
  - spring_petclinic_docker_compose
...

